language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

before_install:
 - go get -u github.com/mattn/goveralls

script:
 - go vet ./...
 - go test -v -cover ./...

after_success:
 - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN
